import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import axios from "../lib/axios";

const Home: NextPage = () => {
  const testEndpoint = async () => {
    try {
      const { data } = await axios.get("http://localhost:3000/api/v1/example", {
        headers: {
          "Content-Type": "application/json",
          Authorization: localStorage.getItem("token") ?? "",
        },
      });
      console.log(data);
    } catch (e) {
      console.error(e);
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <button onClick={testEndpoint}>Test Endpoint</button>
        <Link href="/">Go to home page</Link>
      </main>
    </div>
  );
};

export default Home;
